### ISSUE TITLE
ACME with DNS challenge

### ISSUE THREAD

**Issue by pinki** [mailcow/mailcow-dockerized#1270]
Hi,
is there an easy way to configure ACME to prefer DNS challenges?

**Comment by MAGICCC** [comment]
Not with the current setup.
To be honest it seems the acme-client isn't in development at the moment, I would switch to [acme.sh](https://github.com/Neilpang/acme.sh)
The next 'problem' is to display users that they have to add the TXT records to their DNS or they can use a predefinied script to do it automatically, but not all DNS providers are covered by this -> Layer 8 problems occurs - so I would still use HTTP resources for validation for a project like this

**Comment by christianbur** [comment]
i use let's encypt wildcard certificates and also use acme.sh
Inside the acme.sh contienr the croncob will renew the certificat automatically, and copy the cert to ..../mailcow-dockerized/data/assets/ssl/.
However, I still have to restart Mailcow manually when the certificate file has been renewed. 

docker-compose.yml 
```
version: '3.0'
services:

   acme.sh:
      container_name: acme.sh
      image: neilpang/acme.sh:latest
      command: daemon
      restart: always
      volumes:
        - ./data/acme.sh/:/acme.sh/:rw
        - /PATH-TO-MAILCOW/mailcow-dockerized/data/assets/ssl/:/cert_mailcow/:rw
```
create cert

```
docker  exec acme.sh --issue        --dns xxDNS_PLUGINxx --debug -d example.com -d *.example.com

docker  exec acme.sh --install-cert -d example.com --key-file  /cert_mailcow/key.pem  --fullchain-file /cert_mailcow/cert.pem 
```
