### ISSUE TITLE
Mailcow and nginx-proxy

### ISSUE THREAD

**Issue by daschxx** [mailcow/mailcow-dockerized#1345]
I want to use Mailcow behind a Nginx Proxy in Docker [[https://github.com/jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy)]
I added in docker-compose.override.yml:

```
version: '2.1'
services:

    nginx-mailcow:
      environment:
        - LETSENCRYPT_HOST=${MAILCOW_HOSTNAME}
        - LETSENCRYPT_EMAIL=mail@${MAILCOW_HOSTNAME}
        - VIRTUAL_HOST=${MAILCOW_HOSTNAME}
        - VIRTUAL_PROTO=http
        - VIRTUAL_PORT=80
      networks:
        webproxy:

networks:
  webproxy:
    external:
      name: webproxy
```

in docker-compose.yml:
```
nginx-mailcow:
[...]
#      ports:
#        - "${HTTPS_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:${HTTPS_PORT:-443}"
#        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-80}:${HTTP_PORT:-80}"
```

but now i get error Messages from Watchdog for rspamd and nginx inside mailcow.

I think the problem is the second network, but I have no idea how to solve it.

Is it possible to run Mailcow behind a Proxy inside Docker?

**Comment by stevesbrain** [comment]
Take a read of [this page](https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/) - specifically, don't modify the docker compose, instead, modify mailcow conf file, adjust the "behind the scenes" port of nginx in there, and then point your reverse proxy at that port instead.

**Comment by daschxx** [comment]
When I use 127.0.0.1 in a dockerised nginx proxy, nginx use the docker localhost and not the hosts localhost. My Problem is not to use mailcow behind a proxy runing on host. My problem is runing it behind a proxy runing in another docker-composer instance.

**Comment by stevesbrain** [comment]
Ah, right - in that case, you'd need to make it part of a network, and specify the host/hostname/ip etc. for it (rather than localhost). Either that, or force your nginx container to use bridged networking.

**Comment by daschxx** [comment]
Can you explain it a little bit more.

Now i create a docker-compose project with nginx

```
version: '3'

services:
  server:
    image: nginx:alpine
    restart: always
    volumes:
      - /opt/data/nginx-test/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    networks:
      default:

networks:
  default:
    external:
      name: webproxy
```

the nginx config in /opt/data/nginx-test/conf.d/default.conf

```
# mail.domain.org
upstream mail.domain.org {
	server mailcow_nginx-mailcow_1:8080;
}
server {
	server_name mail.domain.org;
	listen 80 ;
	access_log /var/log/nginx/access.log;
    location / {
	proxy_pass http://mail.domain.org;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        client_max_body_size 100m;
	}
}
```

and the docker-compose.override.yml:

```
version: '2.1'
services:
    nginx-mailcow:
      networks:
        webproxy:

networks:
  webproxy:
    external:
      name: webproxy
```

it seams to work, but watchdog sends me every 5 minutes an email:

> Watchdog: nginx-mailcow service hit the error rate limit
> Service was restarted, please check your mailcow installation.

in the docker logs I can’t find any error. (_docker logs -f mailcow_nginx-mailcow_1_)

Any idea what I make wrong?

**Comment by stevesbrain** [comment]
Is it possible to run the nginx in the foreground so you can perhaps watch it in real time (the one that's restarting)? I'm on my mobile at the moment, so can't test out your config at all right now!

**Comment by daschxx** [comment]
You mean `docker-compose up nginx-mailcow`?
Here the logs:

1. run
```
nginx-mailcow_1      | fd4d:6169:6c63:xxxx::1 - - [01/May/2018:19:14:32 +0000] "GET /forwardinghosts.php HTTP/1.1" 200 27 "-" "-"
nginx-mailcow_1      | 172.22.1.15 - - [01/May/2018:19:14:49 +0000] "HEAD /settings.php HTTP/1.1" 200 0 "-" "-"
mailcow_nginx-mailcow_1 exited with code 0
```
2. run
```
nginx-mailcow_1      | fd4d:6169:6c63:xxxx::1 - - [01/May/2018:19:15:23 +0000] "GET /forwardinghosts.php?host=xxx.xxx.xx.xx HTTP/1.1" 200 19 "-" "curl/7.52.1"
[...]
nginx-mailcow_1      | fd4d:6169:6c63:xxxx::1 - - [01/May/2018:19:18:36 +0000] "GET /settings.php HTTP/1.1" 200 247 "-" "-"
nginx-mailcow_1      | 172.22.1.15 - - [01/May/2018:19:18:37 +0000] "HEAD /forwardinghosts.php HTTP/1.1" 200 0 "-" "-"
mailcow_nginx-mailcow_1 exited with code 0
```
3. run
```
nginx-mailcow_1      | fd4d:6169:6c63:xxxx::1 - - [01/May/2018:19:19:15 +0000] "HEAD /settings.php HTTP/1.1" 200 0 "-" "-"
[...]
nginx-mailcow_1      | fd4d:6169:6c63:xxxx::1 - - [01/May/2018:19:21:59 +0000] "GET /forwardinghosts.php HTTP/1.1" 200 27 "-" "-"
nginx-mailcow_1      | fd4d:6169:6c63:xxxx::1 - - [01/May/2018:19:22:45 +0000] "HEAD /settings.php HTTP/1.1" 200 0 "-" "-"
nginx-mailcow_1      | 172.22.1.15 - - [01/May/2018:19:22:45 +0000] "GET /settings.php HTTP/1.1" 200 247 "-" "-"
mailcow_nginx-mailcow_1 exited with code 0
```

PS: I use the dev branch.
Tomorrow I will try it on a new system with master branch.

**Comment by chrisheinle** [comment]
Can you please also have a look at: [https://stackoverflow.com/questions/50074479/using-mailcow-dockerized-with-a-dockerized-apache2-4](https://stackoverflow.com/questions/50074479/using-mailcow-dockerized-with-a-dockerized-apache2-4) . I am facing a similiar issue but didn't want to open an issue here.

**Comment by daschxx** [comment]
@chrisheinle: The Url ist wrong and the problem is another, you have to proxy to the mailcow hostname, in default: nginx, for testing, try the http port.
```
    ProxyPass / http://nginx:8080/
    ProxyPassReverse / http://nginx:8080/
```

**Comment by daschxx** [comment]
Today I try a new clean master branch mailcow, its the same problem, I have access to the website, but the mailcow nginx container restarts every 5 minutes.

**Comment by stevesbrain** [comment]
@daschxx I'll see if I have some time today to try and replicate the setup/scenario you are using!

**Comment by daschxx** [comment]
I think I found the problem.
In data/Dockerfiles/watchdog/watchdog.sh the funktion to get the container ip returns 2 IPs and so the other comands hits an error.
```
get_container_ip() {
  # ${1} is container
  CONTAINER_ID=
  CONTAINER_IP=
  LOOP_C=1
  until [[ ${CONTAINER_IP} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || [[ ${LOOP_C} -gt 5 ]]; do
    sleep 1
    CONTAINER_ID=$(curl --silent http://dockerapi:8080/containers/json | jq -r ".[] | {name: .Config.Labels[\"com.docker.compose.service\"], id: .Id}" | jq -rc "select( .name | tostring | contains(\"${1}\")) | .id")
    if [[ ! -z ${CONTAINER_ID} ]]; then
      CONTAINER_IP=$(curl --silent http://dockerapi:8080/containers/${CONTAINER_ID}/json | jq -r '.NetworkSettings.Networks[].IPAddress')
    fi
    LOOP_C=$((LOOP_C + 1))
  done
  [[ ${LOOP_C} -gt 5 ]] && echo 240.0.0.0 || echo ${CONTAINER_IP}
}
```

**Comment by daschxx** [comment]
see #1427 and #1409

**Comment by zedtux** [comment]
Thank you @daschxx, you saved me ! 🎉

**Comment by bplein** [comment]
My apologies, I'm running into this after moving mailcow behind a newly installed nginx proxy. 

The proxy is operating correctly, I am able to use Mailcow UI and Sogo, as well as another unrelated node.js app that is behind the same proxy. 

I am using an unmodified docker-compose.yml file (updated to the latest today).

Here are the appropriate sections of my docker-compose.override.yml (I am leaving out my volumes)

```
version: '2.1'
services:
    portainer-mailcow:
      image: portainer/portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/conf/portainer:/data
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - portainer
    nginx-mailcow:
      networks:
        proxy-tier:

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

I have set the appropriate section of mailcow.conf as follows:
```
HTTP_PORT=9080
HTTP_BIND=127.0.0.1

HTTPS_PORT=9443
HTTPS_BIND=127.0.0.1
```

If I exec a shell in the watchdog, and run the same sections of the get_container_ip() function by hand, I get a single string with my 2 IP addresses in it. So the loop is bombing out and the test is testing against 240.0.0.0

Please advise. Maybe I'm just getting tired :)

here is a snippet from "docker network inspect" on the two networks:

`            "895314535f60acd6e581adad1c2d9c61993d48294268f9639de9c17b32d53a28": {
                "Name": "mc_nginx-mailcow_1",
                "EndpointID": "457191b0d2b6abfd7276adbacbb864ffa06ee17ba27f35401646cac696438cb4",
                "MacAddress": "02:42:ac:16:01:0d",
                "IPv4Address": "172.22.1.13/24",
                "IPv6Address": ""
            },`

`           "895314535f60acd6e581adad1c2d9c61993d48294268f9639de9c17b32d53a28": {
                "Name": "mc_nginx-mailcow_1",
                "EndpointID": "4ea42c0f18cf1cf573cac38171b25537e544985440fcc613e80a1f2046f94c1b",
                "MacAddress": "02:42:ac:18:00:05",
                "IPv4Address": "172.24.0.5/16",
                "IPv6Address": ""
            },`
