### ISSUE TITLE
Mailcow behind a proxy with custom letsencrypt SSL certificates

### ISSUE THREAD

**Issue by T-Specht** [mailcow/mailcow-dockerized#1421]
I am using mailcow behind an nginx proxy and would like to have working SSL certificates. My first question is what these certificates are being used for. Are they only used for https connections or also for secure mail transports?

Following first #1129, which did not work, I then tried to link my already generated letsencrypt certificate for the mailcow hostname, autodiscover and autoconfig using #156. 

But when configuring my email client it still gives me a warning message: "The security certificate for this server is invalid or expired."
Also, trying to send an encrypted/signed email from SoGO aborts with "cannot sign email without certificate".

**Comment by andryyy** [comment]
They are used for all secured transfers in Dovecot, Postfix and Nginx.

Set `SKIP_LETS_ENCRYPT=y` in mailcow.conf and run `docker-compose up -d`.
Hard links seem not to work for some setups (depends on your storage driver in Docker, I think). Just copy the files to data/assets/ssl as described in the docs. Symlinks will never work, don't try that. :-) 

Restart nginx-mailcow, postfix-mailcow and dovecot-mailcow after copying the files. It is pretty much that. Just copy the files and restart the services.

**Comment by T-Specht** [comment]
Ok, I will try an actual copy. 👍Do you have any advice on how I could handle automatic certificate updates with certbot when using a copy? 
Oh and yes, I forgot to mention that I already configured `SKIP_LETS_ENCRYPT=y`...

**Comment by T-Specht** [comment]
I still get the warning by my email client after using a copy of the certificate. Which domains should be included in the certificate for it to work? Maybe I missed some?

**Comment by daschxx** [comment]
I have in my

>  docker-compose.override.yml

```
version: '2.1'
services:
    dovecot-mailcow:
      volumes:
        - ./data/assets/ssl:/etc/ssl/mail/:rw
        - /opt/data/nginx/certs/fullchain.pem:/etc/ssl/mail/cert.pem:ro
        - /opt/data/nginx/certs/key.pem:/etc/ssl/mail/key.pem:ro
        - /opt/data/nginx/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
    postfix-mailcow:
      volumes:
        - ./data/assets/ssl:/etc/ssl/mail/:rw
        - /opt/data/nginx/certs/fullchain.pem:/etc/ssl/mail/cert.pem:ro
        - /opt/data/nginx/certs/key.pem:/etc/ssl/mail/key.pem:ro
        - /opt/data/nginx/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
    nginx-mailcow:
      volumes:
        - ./data/assets/ssl:/etc/ssl/mail/:rw
        - /opt/data/nginx/certs/fullchain.pem:/etc/ssl/mail/cert.pem:ro
        - /opt/data/nginx/certs/key.pem:/etc/ssl/mail/key.pem:ro
        - /opt/data/nginx/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
```
so you can use certbot or any other renewer.
