### ISSUE TITLE
Mailcow volumes in other directory

### ISSUE THREAD

**Issue by fawzibr** [mailcow/mailcow-dockerized#1455]
I know there is [this option](https://github.com/mailcow/mailcow-dockerized/issues/493), but (and correct me if I'm mistaken) AFAIK that moves *every* docker volume to that directory, even non-mailcow things. Is there a way to only change the mailcow volumes? Like adding something to mailcow.conf like:

MAILCOW_DATA_DIR=*directory*

or

MAILCOW_VMAIL_DIR=*directory* 
MAILCOW_MYSQL_DIR=*directory*
*etc*

Or is my only option is to edit the docker-compose.yml file for something like that? I really dont want to do that, since that will complicate things with updates. I guess I could make links in /var/lib/docker/volumes for each mailcow volume, but was wondering if there are other options.

**Comment by daschxx** [comment]
You can create a file 

> docker-compose.override.yml
```
version: '2.1'
volumes:
  vmail-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/vmail
      o: bind
  mysql-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/mysql
      o: bind
  redis-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/redis
      o: bind
  rspamd-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/rspamd
      o: bind
  postfix-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/postfix
      o: bind
  crypt-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/crypt
      o: bind
  rspamd-sock:
    driver_opts:
      type: none
      device: /data/mailcow/rspamd-sock
      o: bind
```
