### ISSUE TITLE
include sample for reverse proxy in front of mailcow

### ISSUE THREAD

**Issue by kratan** [mailcow/mailcow-dockerized#1657]
Hi,
https://felixmoessbauer.com/blog-reader/mailcow-reverse-proxy-letsencrypt.html managed it to get work to use a reverse proxy in front of mailcow, so we can use lets encrypt together with mailcow ....

is there any chance to get that into mailcow so people can use port 80/443 for their normal webpages...

greets

**Comment by andryyy** [comment]
Hi, that's part of the docs. Or do I miss something here?

**Comment by kratan** [comment]
hi andryyy, thanks for your replying. i was blind, found it here https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ thanks :). 
I cant find something mentioned about port 80, using same lets encrypt certs and restarting if new certs where installed....maybe there's a chance to have a complete example...?
greets

**Comment by andryyy** [comment]
Hi,
I will add it. But iirc you will find issues where people included their post-hook scripts to be used with certbot. :-)

A post-hook script I think would work:
```
#!/bin/bash
cp /etc/letsencrypt/live/my.domain.tld/fullchain.pem /opt/mailcow-dockerized/data/assets/ssl/cert.pem
cp /etc/letsencrypt/live/my.domain.tld/privkey.pem /opt/mailcow-dockerized/data/assets/ssl/key.pem
postfix_c=$(docker ps -qaf name=postfix-mailcow)
dovecot_c=$(docker ps -qaf name=dovecot-mailcow)
nginx_c=$(docker ps -qaf name=nginx-mailcow)
docker restart ${postfix_c} ${dovecot_c} ${nginx_c}
```

**Comment by kratan** [comment]
thanks, my kid closed it, so i reopened it :-)

**Comment by kratan** [comment]
hi, are there any news on this?
greets

**Comment by bplein** [comment]
I believe I am running into similar issues. 

I recently put together letsencrypt-companion with nginx-proxy in front of Mailcow, so I can run other web sites on the same docker host. It works well with respect to fronting the Mailcow UI and other sites.

My MX is mailhost.example.com (not the real domain, for example only)
My WebUI for mailcow is at example.com (not mailhost). 

I have followed the other instructions at https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/ so my nginx-proxy is proxying only ports 80/443 and NOT SSL traffic for postfix and dovecot. 

The issue is that the SSL cert that mailcow would normally handle for its nginx, dovecot and postfix is stale (it's from the old setup) and I need it to generate for dovecot and postfix. It's attempting to generate for the autoconfig and autodiscover names and failing. This is because MY nginx proxy is getting these requests and failing. 

I know I could generate all the requested certs/names in my proxy and then copy them down to mailcow, but that seems like a hack. 

I was thinking of different ways to solve this, but I can't get my head wrapped around it completely, I'd love your opinion on the best way to do this:

- copy the files from my letsencrypt/nginx-proxy down to mailcow after generation, downside is I could have bugs in my scripting and it ties everything together by paths.
- mount the same volume for certs to both my front end nginx-proxy and the postfix and dovecot locations, via docker-compose.override.yml
- use my proxy to proxy all of the appropriate ports for dovecot and postfix, which would require changes to the mailcow docker-compose setup, possibly more involved that the prior workaround.

Thoughts? I would want my solution to be as forward compatible with mailcow changes as possible... in fact, I'd prefer to use mailcow as un-modified as possible for this very reason. It's a great product an th more I hack around it the more things will break!

**Comment by melonenkind** [comment]
Hi,
@bplein: are there any news on this? Have you find a working solution?
greets

**Comment by bplein** [comment]
Hi @melonenkind,

I was hoping to get direction on the best path to follow from @andryyy before spending too much time on it. But I know from some of his recent posts that he’s very busy right now. 

I might try and work on this today. I will try the second bullet from above first. Will need to figure out how to restart the containers though. The last one is probably the right one but will have more edits to the override file at first glance.

**Comment by bplein** [comment]
the problem I'm running into with mounting the letsencrypt-companion certificate directory is that the file layout is different.

Letsencrypt-companion puts the dhparam.pem in a parent directory and the certs in each of their own directories. The mailcow apps expect the /etc/ssl/mail/ directory to have all of the files. 

I'm going to try hacking this in by copying in (or symlinking) dhparam.pem to see if that's the only remaining thing to get the mailcow postfix and dovecot to use the keys from letsencrypt-companion.

**Comment by bplein** [comment]
OK, some progress! I'd love for @andryyy to chime in with his opinions on this approach. 

I use 2 host names, lets call them example.org and mailhost.example.org. Both are the same IP, the mailhost.example.org is the MX host but I prefer to use example.org for the WebUI, but of course they are all on the same mailcow setup.

I use the letsencrypt-companion to proxy the SoGo and Mailcow UI per the mailcow instructions. That works perfectly.

Then I add this to my docker-compose.override.yml file (in addition to my other overrides):
```
    dovecot-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/:ro
    postfix-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/:ro
```
.... where ../nginx-proxy/ is my letsencrypt companion plus proxy setup. 

Now the one thing that I have to do manually is copy my dhparam.pem from ../nginx-proxy/certs to dhparams.prm in ../nginx-proxy/certs/${MAILCOW_HOSTNAME}. Note the different file names (dhparam vs dhparam**s**)!!! 

So my "to do" list is to figure out how to automate the copy of dhparam.pem to ${MAILCOW_HOSTNAME}/dhparam**s**.pem and how to do this automatically the next time this is re-generated. I tried mounting the dhparams file as a volume into the same directory but it's a RO filesystem and that's not allowed.

**Comment by melonenkind** [comment]
HI,
maybe a hint, you can of course use files like dirs in docker...
.e.g ./nginx-proxy/certs/dhparam.pem:nginx-proxy/certs/${MAILCOW_HOSTNAME/dhparams.pem:ro

maybe that would be an idea?

**Comment by bplein** [comment]
I tried that but got an error about trying to mount a file on a read only directory. I will go back and play with the syntax and see if I had it right.

**Comment by bplein** [comment]
Oh, your example shows paths from host to host, it needs to be from host to container. 
Here is the section from my override:
```
    dovecot-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/:ro
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
    postfix-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/:ro
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
```
And here is the error:

`ERROR: for postfix-mailcow  Cannot start service postfix-mailcow: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/fiomirror/nginx-proxy/certs/dhparam.pem\\\" to rootfs \\\"/var/lib/docker/overlay2/7cace2a13e371095959a97efd3f6946babd9a96203357eb1dab405b2be6c5df6/merged\\\" at \\\"/var/lib/docker/overlay2/7cace2a13e371095959a97efd3f6946babd9a96203357eb1dab405b2be6c5df6/merged/etc/ssl/mail/dhparams.pem\\\" caused \\\"open /var/lib/docker/overlay2/7cace2a13e371095959a97efd3f6946babd9a96203357eb1dab405b2be6c5df6/merged/etc/ssl/mail/dhparams.pem: read-only file system\\\"\"": unknown`

**Comment by bplein** [comment]
If I make the /etc/ssl/mail/ directory non-RO (by leaving off the ro mount parameter), this system now works. 

The directory and files are owned by root and are read-only based on the filesystem. So I think this is secure, although less secure than mounting the whole directory RO. I guess if something could escalate from the postfix or dovecot users to root, they'd be able to manipulate the certs (but not the dhparam file)

**Comment by bplein** [comment]
The current, working example of docker-compose.override.yml now includes:

```
    dovecot-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
    postfix-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
```

**Comment by bplein** [comment]
Now to figure out how to get the letsencrypt-companion to tell postfix and dovecot to restart after a new file is generated (or to see if it automatically picks it up)

**Comment by andryyy** [comment]
Hey Bill, thanks for your reports and solution. Leaving out the "ro" parameter is fine imo.

I wonder if the companion is able to run post-hooks? You could use curl and the socket /var/run/docker.sock to restart the containers. I could help you with the script, but we should make sure wether le-companion is able to run it.

**Comment by MAGICCC** [comment]
Hey may I ask why you use le-companion which doesn't support v2 API yet? Why not using acme.sh which can also use v2 and thus DNS-01
I can write my setup down if I have time...

**Comment by bplein** [comment]
> Hey Bill, thanks for your reports and solution. Leaving out the "ro" parameter is fine imo.
> 
> I wonder if the companion is able to run post-hooks? You could use curl and the socket /var/run/docker.sock to restart the containers. I could help you with the script, but we should make sure wether le-companion is able to run it.

I can look into it, if I find out I'll let you know.  The way it works with containers that it proxies for is that it restarts those containers when there's a change in the cert. I could register the dovecot and postfix containers as a container that it knows about and trigger it that way, I haven't thought through the consequences.

**Comment by bplein** [comment]
> Hey may I ask why you use le-companion which doesn't support v2 API yet? Why not using acme.sh which can also use v2 and thus DNS-01
> I can write my setup down if I have time...

I want to use an out-of-the-box container that I don't have to modify. I don't need wildcard certs yet, the basic letsencrypt-companion https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion does just fine for me now.

But if you are willing to share your example, please do. If it's a "better mousetrap" i'm all for it.

**Comment by melonenkind** [comment]
Hi guys,
are there any news on this?
greets

**Comment by bplein** [comment]
Well it’s running fine with the settings shown above. I have NOT figured out the best way to automate letsencrypt update restart of the two containers after the update but I have a few months to figure that out. Feel free to pick up where we left off :)

**Comment by melonenkind** [comment]
@bplein, thanks for info. Can you poste your reverse proxy config? Or maybe you have your complete example code in some github repo?

greets

**Comment by bplein** [comment]
It's just an unadorned setup for this container (which uses another related container): https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

First I set up a network called "nginx-proxy". That's the shared network that all containers that use the proxy need to be located on (in addition to their own application network, i.e. mailcow-network, etc.)

```
~/docker/nginx-proxy$ cat docker-compose.yml
version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./vhost.d:/etc/nginx/vhost.d"
      - "./html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./certs:/etc/nginx/certs"
    networks:
      - proxy-tier

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
In the mailcow setup I use an unmodified docker-compose.yml for mailcow, and all my edits go into docker-compose.override.yml (you'll see I'm running Portainer in there too, per the mailcow example instructions.) I've redacted my email as REDACTED@example.com below, even though my email address is pretty easy for anyone to deduce.

```
~/docker/mailcow$ cat docker-compose.override.yml
version: '2.1'
services:
    portainer-mailcow:
      image: portainer/portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/conf/portainer:/data
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - portainer
    nginx-mailcow:
      networks:
        proxy-tier:
      environment:
        - VIRTUAL_HOST=${MAILCOW_HOSTNAME},${ADDITIONAL_SAN}
        - VIRTUAL_PORT=9080
        - LETSENCRYPT_HOST=${MAILCOW_HOSTNAME},${ADDITIONAL_SAN}
        - LETSENCRYPT_EMAIL=REDACTED@example.com
    dovecot-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
    postfix-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
volumes:
  vmail-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/vmail
      o: bind
  mysql-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/mysql
      o: bind
  redis-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/redis
      o: bind
  rspamd-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/rspamd
      o: bind
  postfix-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/postfix
      o: bind
  crypt-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/crypt
      o: bind
  rspamd-sock:
    driver_opts:
      type: none
      device: /data/mailcow/rspamd-sock
      o: bind
networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

The environment variables set for nginx-mailcow allow my nginx-proxy services to proxy in front the mailcow-nginx. It's a bit of a waste to double proxy but the overhead is so small and this is just for the WebUI and SoGo, which I rarely use, so no big deal.   

I am thinking of adding the LETSENCRYPT environment variables to postfix and dovecot... if they don't affect it negatively, then the net result will be that letsencrypt-companion will autostart dovecot and postfix after a change in certs, just as it does with any other container registered that way that it normally proxies.

**Comment by bplein** [comment]
one of the requirements of using these examples I've given is that the directory you have mailcow in has to be in the same parent directory as my nginx-proxy (i.e. it gets to those files via ../nginx-proxy). 

I could put all those paths into environment variables in .env and make this more generic.

**Comment by bplein** [comment]
I'm being a bit dumb: letsencrypt-companion doesn't restart other containers. It just listens for changes and if it needs to proxy a new container or a previous container that was proxied changes, it can react to that. Time to look for post-hooks.

**Comment by bplein** [comment]
Someone has asked for this functionality (Restart Containers on Cert Renewal #434) https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/434

**Comment by melonenkind** [comment]
@bplein, great thanks for sharing. if i have time i will try your setup posted above...
greets

**Comment by PMK** [comment]
> Someone has asked for this functionality (Restart Containers on Cert Renewal #434) [JrCs/docker-letsencrypt-nginx-proxy-companion#434](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/434)

PR is merged. I would like to see an example using the nginx-proxy.

**Comment by bplein** [comment]
I'm not sure it's necessary. I can't prove that it works under all circumstances, but when it came time to renew my certs, it appears that dovecot and postfix saw the cert changes and acted appropriately.

**Comment by mvthul** [comment]
> It's just an unadorned setup for this container (which uses another related container): https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
> 
> First I set up a network called "nginx-proxy". That's the shared network that all containers that use the proxy need to be located on (in addition to their own application network, i.e. mailcow-network, etc.)
> 
> ```
> ~/docker/nginx-proxy$ cat docker-compose.yml
> version: '2'
> 
> services:
> 
>   nginx-proxy:
>     image: jwilder/nginx-proxy
>     ports:
>       - "80:80"
>       - "443:443"
>     volumes:
>       - "./vhost.d:/etc/nginx/vhost.d"
>       - "./html:/usr/share/nginx/html"
>       - "/var/run/docker.sock:/tmp/docker.sock:ro"
>       - "./certs:/etc/nginx/certs"
>     networks:
>       - proxy-tier
> 
>   letsencrypt-nginx-proxy-companion:
>     image: jrcs/letsencrypt-nginx-proxy-companion
>     volumes:
>       - "/var/run/docker.sock:/var/run/docker.sock:ro"
>     volumes_from:
>       - "nginx-proxy"
> networks:
>   proxy-tier:
>     external:
>       name: nginx-proxy
> ```
> 
> In the mailcow setup I use an unmodified docker-compose.yml for mailcow, and all my edits go into docker-compose.override.yml (you'll see I'm running Portainer in there too, per the mailcow example instructions.) I've redacted my email as [REDACTED@example.com](mailto:REDACTED@example.com) below, even though my email address is pretty easy for anyone to deduce.
> 
> ```
> ~/docker/mailcow$ cat docker-compose.override.yml
> version: '2.1'
> services:
>     portainer-mailcow:
>       image: portainer/portainer
>       volumes:
>         - /var/run/docker.sock:/var/run/docker.sock
>         - ./data/conf/portainer:/data
>       restart: always
>       dns:
>         - 172.22.1.254
>       dns_search: mailcow-network
>       networks:
>         mailcow-network:
>           aliases:
>             - portainer
>     nginx-mailcow:
>       networks:
>         proxy-tier:
>       environment:
>         - VIRTUAL_HOST=${MAILCOW_HOSTNAME},${ADDITIONAL_SAN}
>         - VIRTUAL_PORT=9080
>         - LETSENCRYPT_HOST=${MAILCOW_HOSTNAME},${ADDITIONAL_SAN}
>         - LETSENCRYPT_EMAIL=REDACTED@example.com
>     dovecot-mailcow:
>       volumes:
>         - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
>         - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
>     postfix-mailcow:
>       volumes:
>         - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
>         - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
> volumes:
>   vmail-vol-1:
>     driver_opts:
>       type: none
>       device: /data/mailcow/vmail
>       o: bind
>   mysql-vol-1:
>     driver_opts:
>       type: none
>       device: /data/mailcow/mysql
>       o: bind
>   redis-vol-1:
>     driver_opts:
>       type: none
>       device: /data/mailcow/redis
>       o: bind
>   rspamd-vol-1:
>     driver_opts:
>       type: none
>       device: /data/mailcow/rspamd
>       o: bind
>   postfix-vol-1:
>     driver_opts:
>       type: none
>       device: /data/mailcow/postfix
>       o: bind
>   crypt-vol-1:
>     driver_opts:
>       type: none
>       device: /data/mailcow/crypt
>       o: bind
>   rspamd-sock:
>     driver_opts:
>       type: none
>       device: /data/mailcow/rspamd-sock
>       o: bind
> networks:
>   proxy-tier:
>     external:
>       name: nginx-proxy
> ```
> 
> The environment variables set for nginx-mailcow allow my nginx-proxy services to proxy in front the mailcow-nginx. It's a bit of a waste to double proxy but the overhead is so small and this is just for the WebUI and SoGo, which I rarely use, so no big deal.
> 
> I am thinking of adding the LETSENCRYPT environment variables to postfix and dovecot... if they don't affect it negatively, then the net result will be that letsencrypt-companion will autostart dovecot and postfix after a change in certs, just as it does with any other container registered that way that it normally proxies.

@bplein Heyy im trying to get it to work for the past days... can you maybe help out?
Im using jwilder nginx-proxy on an existing network already this is my setup (with letsencrypt companion):

- nginx-proxy 
1. certs if generated are in host: /opt/nginx-proxy/certs
2. nginx-proxy (jwilder) container is running on networkname: cloudbox

-cloudbox
network is bridged all my other containers work

Whats steps do i need to try im too confused now.
I tried everything i could find editing docker-compose.yml and docker-compose.override.yml
and editing mailcow.conf as far as i could find info

**Comment by bplein** [comment]
Sorry, I answered on the other thread. 

here's my setup: I have nginx-proxy  with the Letsencrypt Companion installed in a different directory, and refer to it in the override file. I point at its certificate directory.

docker-compose.override.yml
```
version: '2.1'
services:
    clamd-mailcow:
      mem_limit: 1G
    redis-mailcow:
      mem_limit: 1G
    solr-mailcow:
      mem_limit: 1G
    portainer-mailcow:
      image: portainer/portainer
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/conf/portainer:/data
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - portainer
    nginx-mailcow:
      networks:
        proxy-tier:
      environment:
        - VIRTUAL_HOST=${MAILCOW_HOSTNAME},${ADDITIONAL_SAN}
        - VIRTUAL_PORT=9080
        - LETSENCRYPT_HOST=${MAILCOW_HOSTNAME},${ADDITIONAL_SAN}
        - LETSENCRYPT_EMAIL=myemail@example.com
    dovecot-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}:/etc/ssl/mail/
        - ../nginx-proxy/certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
    postfix-mailcow:
      volumes:
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}/fullchain.pem:/etc/ssl/mail/cert.pem:ro
        - ../nginx-proxy/certs/${MAILCOW_HOSTNAME}/key.pem:/etc/ssl/mail/key.pem:ro

volumes:
  vmail-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/vmail
      o: bind
  mysql-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/mysql
      o: bind
  redis-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/redis
      o: bind
  rspamd-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/rspamd
      o: bind
  postfix-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/postfix
      o: bind
  crypt-vol-1:
    driver_opts:
      type: none
      device: /data/mailcow/crypt
      o: bind
  rspamd-sock:
    driver_opts:
      type: none
      device: /data/mailcow/rspamd-sock
      o: bind
networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
