### ISSUE TITLE
Gelf logging driver

### ISSUE THREAD

**Issue by discofris** [mailcow/mailcow-dockerized#191]
I'm trying to send the logs of all mailcow containers to my Graylog server.

I've tried:
- adding this to docker-composer.yml
```
 logging:
      driver: gelf
      options:
        gelf-address: "udp://linsrv-4:12201"
        tag: "logger-test"
```

- adding options to the docker daemon

`DOCKER_OPTS="--log-driver=gelf --log-opt gelf-address=udp://linsrv-4:12201"`

The transport to my Graylog server works, because I had an entry in my Graylog when doing
`docker run --log-driver=gelf --log-opt gelf-address=udp://linsrv-4:12201 busybox echo Hello Graylog`

Surely I'm missing someting. Any idea what?
