### ISSUE TITLE
How to bind IPv4 and IPv6 together?

### ISSUE THREAD

**Issue by pyy** [mailcow/mailcow-dockerized#1978]
Hello everyone,

in file mailcow.conf, we can set mailcow to bind exact IP address, for example
```
# ------------------------------
# Other bindings
# ------------------------------
SMTP_PORT=11.22.33.44:25
SMTPS_PORT=11.22.33.44:465
SUBMISSION_PORT=11.22.33.44:587
...
```
It looks like I can only bind to one IP. But if I have multiple IPv6, how can I also bind with IPv6 at the same time? In other word, how can I bind to more than two IPs at same time, except binding to 0.0.0.0:25 ...

thank you.

**Comment by ngdio** [comment]
Can this be reopened? I'd also like to bind to both ipv4 and ipv6 addresses.

**Comment by imxari** [comment]
Yes, I'd like to bind on both v6 and v4

**Comment by andryyy** [comment]
We need doc updates...

Something like this will work, but does also need IPv4 bindings for all services! If not, it fails:

```
# nano docker-compose.override.yml
version: '2.1'
services:

    dovecot-mailcow:
      ports:
        - '2000:1:1:1:1:1:dead:beaf:143:143'
        - '2000:1:1:1:1:1:dead:beaf:993:993'
        - '2000:1:1:1:1:1:dead:beaf:110:110'
        - '2000:1:1:1:1:1:dead:beaf:995:995'
        - '2000:1:1:1:1:1:dead:beaf:4190:4190'

    postfix-mailcow:
      ports:
        - '2000:1:1:1:1:1:dead:beaf:25:25'
        - '2000:1:1:1:1:1:dead:beaf:465:465'
        - '2000:1:1:1:1:1:dead:beaf:587:587'

    nginx-mailcow:
      ports:
        - '2000:1:1:1:1:1:dead:beaf:80:80'
        - '2000:1:1:1:1:1:dead:beaf:443:443'
```

Edit: IPv4 bindings should look like this:

```
HTTP_PORT=80
HTTP_BIND=1.2.3.4

HTTPS_PORT=443
HTTPS_BIND=1.2.3.4

SMTP_PORT=1.2.3.4:25
SMTPS_PORT=1.2.3.4:465
SUBMISSION_PORT=1.2.3.4:587
IMAP_PORT=1.2.3.4:143
IMAPS_PORT=1.2.3.4:993
POP_PORT=1.2.3.4:110
POPS_PORT=1.2.3.4:995
SIEVE_PORT=1.2.3.4:4190
DOVEADM_PORT=127.0.0.1:19991
```
