### ISSUE TITLE
dovecot-mailcow continous restarting (Without tty error)

### ISSUE THREAD

**Issue by Tsopic** [mailcow/mailcow-dockerized#2061]
**Describe the bug**
When running `docker-compose up` Dovecot keeps restarting. 
Other containers are running fine.

**Expected behaviour**
Should run stable, without continuous restarting

**Logs**

```
Uptime: 72  Threads: 29  Questions: 380  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 5.277
The user `vmail' is already a member of `tty'.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 94475  100 94475    0     0   393k      0 --:--:-- --:--:-- --:--:--  394k
20_blatspammer.cf
70_HS_body.cf
70_HS_header.cf
2018-12-02 01:40:46,871 CRIT Set uid to user 0
2018-12-02 01:40:46,877 INFO supervisord started with pid 1
2018-12-02 01:40:47,880 INFO spawned: 'processes' with pid 79
2018-12-02 01:40:47,883 INFO spawned: 'cron' with pid 80
2018-12-02 01:40:47,886 INFO spawned: 'dovecot' with pid 81
2018-12-02 01:40:47,889 INFO spawned: 'syslog-ng' with pid 82
Dec  2 01:40:47 mail syslog-ng[82]: syslog-ng starting up; version='3.8.1'
2018-12-02 01:40:47,951 INFO exited: dovecot (exit status 89; not expected)
2018-12-02 01:40:48,952 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-02 01:40:48,953 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-02 01:40:48,955 INFO spawned: 'dovecot' with pid 87
2018-12-02 01:40:48,955 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-12-02 01:40:49,016 INFO exited: dovecot (exit status 89; not expected)
2018-12-02 01:40:51,021 INFO spawned: 'dovecot' with pid 89
2018-12-02 01:40:51,082 INFO exited: dovecot (exit status 89; not expected)
2018-12-02 01:40:54,087 INFO spawned: 'dovecot' with pid 91
2018-12-02 01:40:54,147 INFO exited: dovecot (exit status 89; not expected)
2018-12-02 01:40:55,149 INFO gave up: dovecot entered FATAL state, too many start retries too quickly
2018-12-02 01:40:56,153 WARN received SIGQUIT indicating exit request
2018-12-02 01:40:56,153 INFO waiting for cron, processes, syslog-ng to die
Dec  2 01:40:56 mail syslog-ng[82]: syslog-ng shutting down; version='3.8.1'
2018-12-02 01:40:56,256 INFO stopped: syslog-ng (exit status 0)
2018-12-02 01:40:57,259 INFO stopped: cron (terminated by SIGTERM)
2018-12-02 01:40:57,260 INFO stopped: processes (terminated by SIGTERM)

```

**System**

```
 H/W path     Device       Class      Description
================================================
                          system     SR ((^_^))
/0                        bus        SR
/0/0                      memory     128KiB BIOS
/0/4                      processor  Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz
/0/4/5                    memory     448KiB L1 cache
/0/4/6                    memory     4MiB L2 cache
/0/15                     memory     16GiB System Memory
/0/15/0                   memory     8GiB DIMM DDR3 Synchronous 1600 MHz (0.6 ns)
/0/15/1                   memory     DIMM DDR3 Synchronous [empty]
/0/15/2                   memory     8GiB DIMM DDR3 Synchronous 1600 MHz (0.6 ns)
/0/15/3                   memory     DIMM DDR3 Synchronous [empty]
/0/100                    bridge     Atom processor C2000 SoC Transaction Router
/0/100/f                  generic    Atom processor C2000 RCEC
/0/100/13                 generic    Atom processor C2000 SMBus 2.0
/0/100/14    eth0         network    Ethernet Connection I354 2.5 GbE Backplane
/0/100/14.1  eth1         network    Ethernet Connection I354 2.5 GbE Backplane
/0/100/16                 bus        Atom processor C2000 USB Enhanced Host Controller
/0/100/18                 storage    Atom processor C2000 AHCI SATA3 Controller
/0/100/1f                 bridge     Atom processor C2000 PCU
/0/100/1f.3               bus        Atom processor C2000 PCU SMBus
/0/101                    bridge     Atom processor C2000 RAS
/1                        power      CRB Battery 0
/2                        power      OEM Define 5

```
 - Ubuntu 16 server running at scaleway.com
 - letsencrypt_nginx_proxy_companion installed in other container, and mailcow-nginx is sitting in the same network with the proxy companion

**Additional context**
docker-compose.override.yml

 ```
version: '2.1'
 services:
     nginx-mailcow:
       networks:
         - service-proxy
       hostname: 'mail.example.ninja'
       environment:
         - VIRTUAL_HOST=mail.example.ninja,${ADDITIONAL_SAN}
         - VIRTUAL_PORT=80
         - LETSENCRYPT_HOST=mail.example.ninja,${ADDITIONAL_SAN}
         - LETSENCRYPT_EMAIL=info@example.ninja
       volumes:
           - /certs:/etc/ssl/mail

     dovecot-mailcow:
       volumes:
         - /certs/${MAILCOW_HOSTNAME}/:/etc/ssl/mail/
         - /certs/${MAILCOW_HOSTNAME}/dhparam.pem:/etc/ssl/mail/dhparam.pem:ro
     postfix-mailcow:
       volumes:
         - /certs/${MAILCOW_HOSTNAME}/:/etc/ssl/mail/
         - /certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
 networks:
   service-proxy:
     external: true

```

**Comment by andryyy** [comment]
It is failing due to a config error, probably something related to the certificates.

You try enabling debugging in Dovecot.

**Comment by Tsopic** [comment]
Dang not much help.

I used these configuration lines in dovecot.conf

```
mail_debug = yes
auth_debug = yes
log_path = syslog
auth_verbose = yes
auth_debug_passwords = yes
auth_verbose_passwords = yes
disable_plaintext_auth = yes
```

Was able to detect this line
`dovecot-mailcow_1_8491363ba703 | sievec: Debug: mail_crypt_plugin: mail_crypt_curve setting missing - generating EC keys disabled`

 but not sure if it is the blocker.

## Full logs 

```
mailcowdockerized_dovecot-mailcow_1_8491363ba703 exited with code 0
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Loading modules from directory: /usr/local/lib/dovecot
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib01_acl_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib05_mail_crypt_acl_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib10_mail_crypt_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib10_quota_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib15_notify_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_listescape_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_mail_log_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<40><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_zlib_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Effective uid=0, gid=0, home=/root
dovecot-mailcow_1_8491363ba703 | sievec: Debug: mail_crypt_plugin: mail_crypt_curve setting missing - generating EC keys disabled
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Quota root: name=Userquota backend=dict args=:proxy::sqlquota
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Quota grace: root=Userquota bytes=0 (10%)
dovecot-mailcow_1_8491363ba703 | sievec: Debug: dict quota: user=root, uri=proxy::sqlquota, noenforcing=0
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Loading modules from directory: /usr/local/lib/dovecot
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib01_acl_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib05_mail_crypt_acl_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib10_mail_crypt_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib10_quota_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib15_notify_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_listescape_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_mail_log_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<41><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_zlib_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Effective uid=0, gid=0, home=/root
dovecot-mailcow_1_8491363ba703 | sievec: Debug: mail_crypt_plugin: mail_crypt_curve setting missing - generating EC keys disabled
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Quota root: name=Userquota backend=dict args=:proxy::sqlquota
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Quota grace: root=Userquota bytes=0 (10%)
dovecot-mailcow_1_8491363ba703 | sievec: Debug: dict quota: user=root, uri=proxy::sqlquota, noenforcing=0
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Loading modules from directory: /usr/local/lib/dovecot
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib01_acl_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib05_mail_crypt_acl_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib10_mail_crypt_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib10_quota_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib15_notify_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_listescape_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_mail_log_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec(root)<42><>: Debug: Module loaded: /usr/local/lib/dovecot/lib20_zlib_plugin.so
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Effective uid=0, gid=0, home=/root
dovecot-mailcow_1_8491363ba703 | sievec: Debug: mail_crypt_plugin: mail_crypt_curve setting missing - generating EC keys disabled
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Quota root: name=Userquota backend=dict args=:proxy::sqlquota
dovecot-mailcow_1_8491363ba703 | sievec: Debug: Quota grace: root=Userquota bytes=0 (10%)
dovecot-mailcow_1_8491363ba703 | sievec: Debug: dict quota: user=root, uri=proxy::sqlquota, noenforcing=0
dovecot-mailcow_1_8491363ba703 | The user `vmail' is already a member of `tty'.
dovecot-mailcow_1_8491363ba703 |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
dovecot-mailcow_1_8491363ba703 |                                  Dload  Upload   Total   Spent    Left  Speed
100 94475  100 94475    0     0   338k      0 --:--:-- --:--:-- --:--:--  339k
dovecot-mailcow_1_8491363ba703 | 20_blatspammer.cf
dovecot-mailcow_1_8491363ba703 | 70_HS_body.cf
dovecot-mailcow_1_8491363ba703 | 70_HS_header.cf
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:47,004 CRIT Set uid to user 0
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:47,010 INFO supervisord started with pid 1
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:48,014 INFO spawned: 'processes' with pid 79
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:48,017 INFO spawned: 'cron' with pid 80
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:48,021 INFO spawned: 'dovecot' with pid 81
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:48,024 INFO spawned: 'syslog-ng' with pid 82
dovecot-mailcow_1_8491363ba703 | Dec  6 05:16:48 mail syslog-ng[82]: syslog-ng starting up; version='3.8.1'
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:48,085 INFO exited: dovecot (exit status 89; not expected)
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:49,087 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:49,087 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:49,090 INFO spawned: 'dovecot' with pid 87
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:49,091 INFO success: syslog-ng entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:49,153 INFO exited: dovecot (exit status 89; not expected)
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:51,159 INFO spawned: 'dovecot' with pid 89
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:51,220 INFO exited: dovecot (exit status 89; not expected)
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:54,225 INFO spawned: 'dovecot' with pid 91
dovecot-mailcow_1_8491363ba703 | 2018-12-06 05:16:54,287 INFO exited: dovecot (exit status 89; not expected)

```

**Comment by andryyy** [comment]
I cannot help with custom stuff. I still guess it is something related to the cert mount. Maybe permissions?

**Comment by Tsopic** [comment]
Thank you for quick answer, it indeed was issue of certs. The nginx-proxy was unable to generate all of the certs needed. I changed the Virtualhost format in docker-compose.override.yml now i'm getting 502 from proxy. 

```
nginx.1    | 2018/12/06 11:57:37 [error] 3758#3758: *5572 connect() failed (111: Connection refused) while connecting to upstream, client: 27.79.228.11, server: mail.example.ninja, request: "GET / HTTP/2.0", upstream: "http://172.19.0.7:80/", host: "mail.example.ninja"
nginx.1    | 2018/12/06 11:57:37 [warn] 3758#3758: *5572 upstream server temporarily disabled while connecting to upstream, client: 27.79.228.11, server: mail.example.ninja, request: "GET / HTTP/2.0", upstream: "http://172.19.0.7:80/", host: "mail.example.ninja"
```

New docker-compose

```
 version: '2.1'
 services:
     nginx-mailcow:
       networks:
         - service-proxy
         - mailcow-network
       hostname: "mail.example.ninja"
       environment:
           VIRTUAL_HOST: "mail.example.ninja"
           VIRTUAL_PORT: "80"
           LETSENCRYPT_HOST: "mail.example.ninja"
           LETSENCRYPT_EMAIL: "info@example.ninja"
       volumes:
           - /certs/${MAILCOW_HOSTNAME}/:/etc/ssl/mail:ro

     dovecot-mailcow:
       networks:
         - mailcow-network
       volumes:
         - /certs/${MAILCOW_HOSTNAME}/:/etc/ssl/mail/
        #- /certs/${MAILCOW_HOSTNAME}/dhparams.pem:/etc/ssl/mail/dhparams.pem:ro
     postfix-mailcow:
       networks:
         - mailcow-network
       volumes:
         - /certs/${MAILCOW_HOSTNAME}/:/etc/ssl/mail/
         - /certs/dhparam.pem:/etc/ssl/mail/dhparams.pem:ro
 networks:
   service-proxy:
     external: true
```
