### ISSUE TITLE
Cannot start TLS: handshake failure

### ISSUE THREAD

**Issue by tehXor** [mailcow/mailcow-dockerized#2185]
Recently i'm getting `Cannot start TLS: handshake failure` for gmx.de and web.de recipients. Other provider like GMail work. However there are a lot of mails to GMX and web.de apperently.

Now I'm not sure if the problem lies on my end, within mailcow or GMX/web.de and the first question is, what's the best way to debug this problem in the containers? All I get from the logs is this:

```
1/16/2019, 1:31:28 AM | info | SSL_connect error to mx01.emig.gmx.net[212.227.17.5]:25: Connection timed out
1/16/2019, 1:31:28 AM | info | 8BE0C60724: Cannot start TLS: handshake failure
1/16/2019, 1:31:28 AM | info | SSL_connect error to mx00.emig.gmx.net[212.227.15.9]:25: Connection timed out
1/16/2019, 1:31:28 AM | info | B980C60729: Cannot start TLS: handshake failure
1/16/2019, 1:31:27 AM | info | SSL_connect error to mx-ha02.web.de[212.227.17.8]:25: Connection timed out
1/16/2019, 1:31:27 AM | info | 5EDA56072C: Cannot start TLS: handshake failure
```
...only a lot more.

Since I saw a timeout I already started by installing inetutils in the postfix container to check if it basically can connect to the hosts in question and that works. So it probably really is some specific SSL/TLS problem.

The problem started with a version which was around 4 weeks ago (but the problem itself came up just recently). I now upgraded to the recent master branch and regarding SSL/TLS my postfix configuration is basically the same as in `master`. This problem still persists though.

Any hint to better debug this or temporally workaround (even if unsecure) would be welcome. Thanks!

**Comment by andryyy** [comment]
I have seen this happening with a wrong MTU.

**Comment by tehXor** [comment]
Very helpful tip @andryyy thanks a lot - and this made all further troubleshooting invalid since exactly that was the problem. Our VMs got moved to a new virtual network with a MTU of 1400 two days ago...

The fast solution is adding `com.docker.network.driver.mtu` to the docker-compose file so that the first part of the network looks like this:

```
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
```

In our case we will now also check if there are better global options, which doesn't involve updatating the docker-compose files of every project. Should we find one, I will add it here.

**Comment by andryyy** [comment]
Nice! :)

**Comment by rtulke** [comment]
Same error here and the hint with mtu does not work for me any idea?

part of my docker-compose.yml:

```
...
...
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
```

**Undelivered Mail Returned to Sender Message:**

```
This is the mail system at host mx.foobar.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                  The mail system

<webmaster@xmail.com>: Cannot start TLS: handshake failure
Reporting-MTA: dns; mx.foobar.com
X-Postcow-Queue-ID: BC4BB880F59
X-Postcow-Sender: rfc822; billing@host.com
Arrival-Date: Thu, 21 Mar 2019 13:23:53 +0100 (CET)

Final-Recipient: rfc822; webmaster@xmail.com
Original-Recipient: rfc822;webmaster@xmail.com
Action: failed
Status: 5.7.5
Diagnostic-Code: X-Postcow; Cannot start TLS: handshake failure
Von: Billing Service <billing@host.com>
Betreff: Ihre Rechnung
Datum: 21. März 2019 um 13:23:46 MEZ
An: Customer Name <webmaster@xmail.com>
```
