### ISSUE TITLE
Use Apache Tika to index attachments

### ISSUE THREAD

**Issue by jhesketh** [mailcow/mailcow-dockerized#2334]
Feature request to index attachments use Apache's Tika: https://wiki2.dovecot.org/Plugins/FTS

**Comment by Braintelligence** [comment]
That would be a killer feature

**Comment by jhesketh** [comment]
Shouldn't be too hard to copy the SOLR container configuration (hopefully!). I might have a stab at this next time I get some free cycles but I'm not familiar with Tika or what it might need to be persistent etc.

**Comment by soulsymphonies** [comment]
Yesterday evening I did actually, out of curiousity, decide to integrate Apache's Tika for some testing, with my mailcow installation.

It was quite easy and works smoothly so far, indexing my doc, docx and pdf files :)

I used this repository https://github.com/LogicalSpark/docker-tikaserver to get a docker container with tika server running, which works quite well

So this is the solution I used, I just added two files, some extra config in the docker-compose.override.yml and some extra dovecot config in the extra.conf file in dovecot's config folder.

**/opt/mailcow-dockerized/docker-compose.override.yml**
```
version: '2.1'
services:
  tika-server-mailcow:
    image: logicalspark/docker-tikaserver
    restart: always
    dns: ${IPV4_NETWORK:-172.22.1}.254
    expose:
      - "9998"
    networks:
      mailcow-network:
        aliases:
          - tika-server

```
**/opt/mailcow-dockerized/data/conf/dovecot/extra.conf**
```
plugin {
  fts_tika = http://tika-server:9998/tika/
}
```

Maybe this will work for you as well :)

**Comment by Braintelligence** [comment]
Thank you so much for sharing @soulsymphonies - maybe @andryyy has an easier time now implementing this, if he wants to 😸. I'm all for it! 👍

**Comment by kaechele** [comment]
I use this in my `docker-compose.override.yml`:
```
version: '2.1'
services:

    tika-mailcow:
      image: apache/tika:latest-full
      restart: always
      dns: ${IPV4_NETWORK:-172.22.1}.254
      ports:
        - "${TIKA_PORT:-127.0.0.1:9998}:9998"
      networks:
        mailcow-network:
          aliases:
            - tika
```

And then in `data/conf/dovecot/extra.conf`:
```
plugin {
  fts_tika = http://tika:9998/tika/
}
```

Running this together with fts-solr currently will lead to the fts-indexer constantly segfaulting. A [fix was commited][1] to the dovecot repo only a few days ago, so it will probably land in a dovecot version after 2.3.14.

[1]: https://github.com/dovecot/core/commit/cd17ae1d770d2376802a3e53a9ec8f72cd8ac5c2
