### ISSUE TITLE
Custom interface name for mailcow-network

### ISSUE THREAD

**Issue by SomeGeek** [mailcow/mailcow-dockerized#2403]
Is it supported to have a custom mailcow-network bridge-interface name?

To do so, one can add:

`networks:
    mailcow-network:
      driver_opts:
         com.docker.network.bridge.name: br-mailcow`

in docker-compose.override.yml.

However, when I start mailcow, it throws errors like:

"user specified IP address is supported only when connecting to networks with user configured subnets" for some containers.

A custom interface name would managing firewall rules a lot easier, as with every reboot the interface name is changed to br-{random string}.

**Comment by andryyy** [comment]
I think you need to add the whole "networks:" part to your override, not just the parts you are actually trying to override.

Like:

```
networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      foot: "bar"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.22.1}.0/24
        - subnet: ${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
```
