### ISSUE TITLE
Fresh Install - No Reverse Proxy - ACME - SSL - HTTP validation failed

### ISSUE THREAD

**Issue by sfsr12** [mailcow/mailcow-dockerized#2462]
CentOS 7 64 Bit Minimal
Fresh Install
No Reverse Proxy

Installed following documentation.

ACME is unable to generate SSL certs
```
Confirmed A record xxx.xxx.xxx.xxx, but HTTP validation failed
```
Commands asked for in issue submission form:
```sh
# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```

```sh
# docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69
```

Looking at lots of other similar issues this command seems to be relevant:

```sh
# docker-compose exec acme-mailcow curl -4 http://${MAILCOW_HOSTNAME}/.well-known/acme-challenge/1 --write-out %{http_code}
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.

curl: (7) Failed to connect to mail.redacted.com port 80: Host is unreachable
```

Same result for IPv6

I have no idea what the issue is.  I have reinstalled the OS multiple times on the VM - spun up a new one (KVM virtualization).  Same result.

I can access http://mail.redacted.com/.well-known/acme-challenge/1 externally from the outside world - and can access it on the host.  But when executed in the docker ACME context it is unreachable.

Been trying all day - any help would be appreciated.

**Comment by andryyy** [comment]
Turn off firewalld or reconfigure it to allow whatever it blocks. I've had no time to check which rule is blocking it.

**Comment by sfsr12** [comment]
Holy crap - that worked.  I didn't even think to check that since I could get to it externally.

You are freaking awesome - an answer in like 4 minutes.

So, is this a known issue that will be resolved in the future - will it always need to be run with firewalld disabled?

**Comment by andryyy** [comment]
I need to find out which rule is needed to permanently allow this connection. :-( Perhaps we should give the bridge a fixed name to make it easier to allow connections from the mailcow network to wherever. @mkuron ?

**Comment by mkuron** [comment]
Sounds reasonable.

**Comment by carlbennett** [comment]
I'm having this issue too. Been using firewalld with no issue, suddenly issue begins within the last month or two. What was the resolution? Simply disabling firewalld and restarting containers gives me an error that it can't configure the bridge.

Kind of urgent. The certificates expired without me noticing, due to this issue.

**Comment by carlbennett** [comment]
To those coming here with firewalld installations, I discovered that the `public` zone was missing all of its whitelisted services.

```
[root@mail ~]# firewall-cmd --list-all-zones
...
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: dhcpv6-client ssh
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

...
```

Per documentation at https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/#firewall-ports, it is necessary to tell firewalld to allow certain services/ports. The following does that.

```
[root@mail ~]# firewall-cmd --permanent --zone public --add-service http
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service https
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service imap
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service imaps
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service pop3
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service pop3s
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service smtp-submission
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service smtps
success
[root@mail ~]# firewall-cmd --permanent --zone public --add-service managesieve
success
```

Then simply reload firewalld and restart mailcow daemons:

```
[root@mail ~]# firewall-cmd --reload
success
```
```
[root@mail ~]# cd /opt/mailcow-dockerized
[root@mail mailcow-dockerized]# docker-compose down
...
[root@mail mailcow-dockerized]# docker-compose up -d
...
```

This seems to have resolved the issue for me.

The firewalld public zone should have the following services now.

```
[root@mail mailcow-dockerized]# firewall-cmd --zone public --list-all
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: dhcpv6-client ssh http https imap imaps pop3 pop3s smtp-submission smtps managesieve
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

```

Checking the logs of acme-mailcow container look good.

```
[root@mail mailcow-dockerized]# docker-compose logs acme-mailcow
...
acme-mailcow_1       | Certificate will not expire
acme-mailcow_1       | Sat Apr  6 09:08:51 UTC 2019 - Certificate validation done, neither changed nor due for renewal, sleeping for another day.
```
