### ISSUE TITLE
Dovecot keeps restarting after Mailcow update: "No such file or directory"

### ISSUE THREAD

**Issue by DatAres37** [mailcow/mailcow-dockerized#3013]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

My Dovecot container keeps restarting after I updated Mailcow with the update script. I tried updating it before (some weeks ago) with the same outcome. The logs are:
```
Uptime: 2  Threads: 28  Questions: 225  Slow queries: 0  Opens: 35  Flush tables: 1  Open tables: 27  Queries per second avg: 112.500
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 7  Threads: 28  Questions: 250  Slow queries: 0  Opens: 36  Flush tables: 1  Open tables: 28  Queries per second avg: 35.714
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 10  Threads: 28  Questions: 343  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 34.300
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 12  Threads: 28  Questions: 344  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 28.666
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 15  Threads: 28  Questions: 345  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 23.000
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 19  Threads: 28  Questions: 346  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 18.210
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 24  Threads: 28  Questions: 353  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 14.708
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 32  Threads: 28  Questions: 354  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 11.062
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 47  Threads: 28  Questions: 355  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 7.553
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 74  Threads: 28  Questions: 448  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 6.054
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 127  Threads: 29  Questions: 555  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 4.370
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 189  Threads: 29  Questions: 746  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 3.947
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 252  Threads: 29  Questions: 845  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 3.353
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 313  Threads: 29  Questions: 1056  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 3.373
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 376  Threads: 29  Questions: 1155  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 3.071
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 438  Threads: 29  Questions: 1354  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 3.091
cat: /etc/dovecot/global_sieve_after: No such file or directory
Uptime: 500  Threads: 29  Questions: 1453  Slow queries: 0  Opens: 38  Flush tables: 1  Open tables: 30  Queries per second avg: 2.906
cat: /etc/dovecot/global_sieve_after: No such file or directory
```
Compose part:
```
dovecot-mailcow:
      image: mailcow/dovecot:1.89
      build: ./data/Dockerfiles/dovecot
      dns:
        - ${IPV4_NETWORK:-172.22.1}.254
      cap_add:
        - NET_BIND_SERVICE
      volumes:
        - /etc/nginx/certs/sub.domain.tld/fullchain.pem:/etc/ssl/mail/cert.pem:ro
        - /etc/nginx/certs/sub.domain.tld/key.pem:/etc/ssl/mail/key.pem:ro
        - ./data/conf/dovecot:/usr/local/etc/dovecot
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - ./data/conf/sogo/:/etc/sogo/
        - ./data/conf/phpfpm/sogo-sso/:/etc/phpfpm/
        - vmail-vol-1:/var/vmail
        - vmail-attachments-vol-1:/var/attachments
        - crypt-vol-1:/mail_crypt/
        - ./data/conf/rspamd/custom/:/etc/rspamd/custom
        - ./data/assets/templates:/templates
        - rspamd-vol-1:/var/lib/rspamd
        - mysql-socket-vol-1:/var/run/mysqld/
      environment:
        - LOG_LINES=${LOG_LINES:-9999}
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - IPV4_NETWORK=${IPV4_NETWORK:-172.22.1}
        - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
        - MAILDIR_GC_TIME=${MAILDIR_GC_TIME:-1440}
        - ACL_ANYONE=${ACL_ANYONE:-disallow}
        - SKIP_SOLR=${SKIP_SOLR:-y}
        - MAILDIR_SUB=${MAILDIR_SUB:-}
      ports:
        - "${DOVEADM_PORT:-127.0.0.1:19991}:12345"
        - "${IMAP_PORT:-143}:143"
        - "${IMAPS_PORT:-993}:993"
        - "${POP_PORT:-110}:110"
        - "${POPS_PORT:-995}:995"
        - "${SIEVE_PORT:-4190}:4190"
      restart: always
      tty: true
      ulimits:
        nproc: 65535
        nofile:
          soft: 20000
          hard: 40000
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        mailcow-network:
          ipv4_address: ${IPV4_NETWORK:-172.22.1}.250
          aliases:
            - dovecot
        nextcloud:
          ipv4_address: 172.20.0.6
          aliases:
            - sub.domain.tld
```
The missing file is definitely under /data/conf/dovecot:
```
-rw-r--r-- 1 root root    8 Okt  6 18:38 acl_anyone
-rw-r--r-- 1 root root 9181 Okt  6 19:05 dovecot.conf
-rw-r--r-- 1 root root   78 Okt  6 18:38 dovecot-master.passwd
-rw-r--r-- 1 root root   46 Okt  6 18:38 dovecot-master.userdb
-rw-r--r-- 1 root root  553 Jun 22 18:22 global_sieve_after
-rw-r--r-- 1 root root  140 Jun 22 18:22 global_sieve_before
drwxr-xr-x 2 root root 4096 Jun 22 18:22 ldap
-rw-r--r-- 1 root root   80 Okt  6 18:38 mail_plugins
-rw-r--r-- 1 root root  121 Okt  6 18:38 mail_plugins_imap
-rw-r--r-- 1 root root   70 Okt  6 18:38 mail_plugins_lmtp
-rw-r--r-- 1 root root  207 Okt  6 18:38 shared_namespace.conf
drwxr-xr-x 2 root root 4096 Jun 22 19:41 sql
```

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

1. I run the update script with sudo ./update.sh --ours
2. The update runs fine without any errors or warnings
3. Every container is up and running except the Dovecot one

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [ ] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04.3 LTS |
| Is Apparmor, SELinux or similar active? | Standard Ubuntu Apparmor service |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8GB RAM, 4 Cores |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.24.1 |
| Reverse proxy (custom solution) | I'm running a Nginx Reverse Proxy in front of MC |
