### ISSUE TITLE
Postfix docker build fails: layer does not exist

### ISSUE THREAD

**Issue by sargreal** [mailcow/mailcow-dockerized#3397]
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand, that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

In the Dockerfile for postfix, the copy line for adding the `stop-supervisor.sh` script is duplicated:
https://github.com/mailcow/mailcow-dockerized/blob/e28a1766391183151464b2ba12482443dae2cf59/data/Dockerfiles/postfix/Dockerfile#L43-L48

For some reason and in some configurations this results in the failing of the docker build with the following message:
```
Step 15/21 : COPY stop-supervisor.sh /usr/local/sbin/stop-supervisor.sh
 ---> 3c2d7bf20a78
Step 16/21 : COPY docker-entrypoint.sh /docker-entrypoint.sh
Service 'postfix-mailcow' failed to build: failed to export image: failed to create image: failed to get layer sha256:95445697c22b782ba3cb5ed5ec28bbfffe5d064c37a4f3873d4ecc8991790bba: layer does not exist
```
This is related to https://github.com/moby/moby/issues/37965

**Docker container logs of affected containers**:

Nothing because not concerned with running the containers

**Reproduction of said bug**:

Not sure, happened when running a docker-compose build in a gitlab ci pipeline with docker:dind as service (i.e. connected to the docker server via tcp). 

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | debian 10 |
| Is Apparmor, SELinux or similar active? | no |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | nothing |
| Server/VM specifications (Memory, CPU Cores) | 64GB RAM, 8 cores |
| Docker Version (`docker version`) | 19.03.7 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4 |
| Reverse proxy (custom solution) | traefik |

- Output of docker and docker-compose version:
```
$ docker -l debug version
 Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:19:42 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c199a2
  Built:            Wed Mar  4 01:19:50 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
$ docker-compose version
 docker-compose version 1.25.4, build unknown
 docker-py version: 4.2.0 
 CPython version: 3.8.2
 OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
Relevant information from `docker-compose.override.yml` and `.gitlab-ci.yml`:
```
.build-template:
  tags:
    - docker
    - build
  services:
    - docker:19.03-dind
  variables:
    IMAGE_HOME: $CI_REGISTRY_IMAGE
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker -l debug version
    - docker-compose version
  script:
    - docker-compose pull -q --ignore-pull-failures
    - docker-compose build --progress plain
    - docker image ls
    - docker-compose push

build dev:
  stage: build
  extends: .build-template
  variables:
    STABILITY: -$CI_COMMIT_REF_SLUG
  except:
    - master
  only:
    - branches

build-prod:
  stage: build
  extends: .build-template
  only:
    - master
```
```
  postfix-mailcow:
    image: ${IMAGE_HOME}/postfix:1.46.1${STABILITY}
    build: ./data/Dockerfiles/postfix
```
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.

Nothing
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

nope
