### ISSUE TITLE
Move volumes away from /var/lib/docker/volumes to project folder - failure

### ISSUE THREAD

**Issue by RedJohn14** [mailcow/mailcow-dockerized#4072]
Hello everyone,

I want to move all volumes from **/var/lib/docker/volumes** to my project folder inside a **/data/volumes** folder. I have created some **docker-compose.override.yml** e.g. with this volumes

```
volumes:
   vmail-vol-1:
   driver: local
   driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/mailcow-dockerized/data/volumes/vmail-vol-1'
```

But mailcow create everytime volumes in `/var/lib/docker/volumes` any ideas how I can fix it and move volumes to another folder?

I have used this manuel:

https://mailcow.github.io/mailcow-dockerized-docs/u_e-dovecot-vmail-volume/

But I want to move ALL volumes.

```
   vmail-index-vol-1:
   driver: local
   driver_opts:
      type: 'none'
      o: 'bind'
      device: '/opt/docker/mailcow-dockerized/data/volumes/vmail-index-vol-1'
```
