### ISSUE TITLE
Error parsing configuration file on setting up borgmatic backup

### ISSUE THREAD

**Issue by holzhannes** [mailcow/mailcow-dockerized#4146]
I am using the latest version of Mailcow and I did set up borgmatic as [described in the documentation](https://mailcow.github.io/mailcow-dockerized-docs/third_party-borgmatic/). When I try to run: 
`docker-compose exec borgmatic-mailcow borgmatic init --encryption repokey-blake2` the following error occurs

```
summary:
/etc/borgmatic.d/config.yaml: Error parsing configuration file
An error occurred while parsing a configuration file at /etc/borgmatic.d/config.yaml:
mapping values are not allowed in this context
  in "/etc/borgmatic.d/config.yaml", line 3, column 9
/etc/borgmatic/config.yaml /etc/borgmatic.d /root/.config/borgmatic/config.yaml /root/.config/borgmatic.d: No valid configuration files found
```

I have checked `data/conf/borgmatic/etc/config.yaml` several times to see if there is a misuse of tabs or the indentation is wrong, but I can't find anything`

```
source mailcow.conf
cat <<EOF > data/conf/borgmatic/etc/config.yaml
location:
    source_directories:
        - /mnt/source
    repositories:
        - USER@rsync.hidrive.strato.com:mailcow
    remote_path: users/USER/mailcow

retention:
    keep_hourly: 24
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6

hooks:
    mysql_databases:
        - name: ${DBNAME}
          username: ${DBUSER}
          password: ${DBPASS}
          options: --default-character-set=utf8mb4
EOF
```
