### ISSUE TITLE
Container hostname help

### ISSUE THREAD

**Issue by pikaxc** [mailcow/mailcow-dockerized#437]
How can I stablish my container hostname: 
When I check headers theres something in from: 
Raw header:
Received: from 22aed47e552b (mailcowdockerized_sogo-mailcow_1.mailcowdockerized_mailcow-network [container's ip])

Is it possible to setup my hostname instead?

I'm gonna be donating for your work thank you.

**Comment by andryyy** [comment]
Hi,

You can set this by using "hostname" in the docker-compose.yml file, like this:

```
    sogo-mailcow:
      image: mailcow/sogo:1.2
      build: ./data/Dockerfiles/sogo
      depends_on:
        unbound-mailcow:
          condition: service_healthy
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
      restart: always
      hostname: sogo.mailcow.internal
      logging:
        options:
          max-size: "5m"
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          ipv4_address: 172.22.1.252
          aliases:
            - sogo
```
