### ISSUE TITLE
phpmyadmin container

### ISSUE THREAD

**Issue by rucksman** [mailcow/mailcow-dockerized#482]
I tried to run a phpmyadmin container alongside mailcow for the ease of database administration. Unfortunately I was not able to reach the container via the browser. I have to admit that I am very new to docker. I did use the container [phpmyadmin/phpmyadmin](https://hub.docker.com/r/phpmyadmin/phpmyadmin/) and tried it first with their [docker-compose snippet](https://docs.phpmyadmin.net/en/latest/setup.html#using-docker-compose). Somehow it ewas clear to me that I would have to link it to the mailcow containers (ngins, mariadb), so it was not surprising that calling http://mail.mydomain.tld:8080 did not work. So I tried it without docker-compose:
````docker run --name myadmin -d --net mailcowdockerized_mailcow-network --link mailcowdockerized_mysql-mailcow_1:db --link mailcowdockerized_nginx-mailcow_1:web -p 8080:80 phpmyadmin/phpmyadmin````
But this did not work either. Could someone please be so kind and give me a hint how to get the phpmyadmin container running?

**Comment by chaosbunker** [comment]
This should work:-)

```
docker run --rm -d --name phpmyadmin --env PMA_HOST=mysql-mailcow --network mailcowdockerized_mailcow-network -p 8181:80 phpmyadmin/phpmyadmin
```

head to http://mail.mydomain.tld:8181 and you should be able to log in.

I tried to figure out what to add in data/conf/nginx/site.conf to get it via https://mail.mydomain.tld/pma but it wouldn't load the assets. i guess somethings missing in the location block, that directs it to the right place. 

```
upstream phpmyadmin {
	server phpmyadmin:80;
}


[...]


location /pma/ {
    proxy_pass http://phpmyadmin/;
    proxy_set_header X-Real-IP  $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

```

nginx gets to the container, source shows html, but some assets can't be found
<img width="662" alt="screen shot 2017-08-03 at 19 12 20" src="https://user-images.githubusercontent.com/16366980/28934077-d32ea0e0-787f-11e7-8f4d-711ad85bcfb2.png">

i also tried this in docker-compose.yml, but same problem. it's accessible via http://mail.mydomain.tld:8181 but not https://mail.mydomain.tld/pma

```
    phpmyadmin-mailcow:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mysql-mailcow
      ports:
        - 8181:80
      environment:
        - PMA_HOST=mysql-mailcow
      dns_search: mailcow-network
      dns:
        - 172.22.1.254
      environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: ${DBROOT}
        PMA_HOST: mysql-mailcow
        PMA_ABSOLUTE_URI: "https://${MAILCOW_HOSTNAME}/pma"
      networks:
        mailcow-network:
          ipv4_address: 172.22.1.44
          aliases:
            - phpmyadmin

```

anyone else know how to get the location block right?

**Comment by rucksman** [comment]
Unfortunately not working for me - not the command line version and also not the composer version. The server does not answer.

**Comment by chaosbunker** [comment]
After doing the docker run command for phpmyadmin that I posted, can you try

`docker-compose exec nginx-mailcow sh -c "ping phpmyadmin"`

and you have to access phpmyadmin via http not https while it is not properly set up via nginx location

So try to access http://mailcow.host:8181

**Comment by rucksman** [comment]
Sorry for not mentioning, but I tried http with no success.

UPDATE: I closed this by mistake. Can I open it again?

**Comment by chaosbunker** [comment]
You should be able to reopen it, i think?

can you do exactly the following (let me know, if your mailcow-dockerized directory is called differently):

```
docker run --rm -d --name phpmyadmin --env PMA_HOST=mysql-mailcow --network mailcowdockerized_mailcow-network -p 8181:80 phpmyadmin/phpmyadmin
```

```
docker-compose exec nginx-mailcow sh -c "ping phpmyadmin"
```

can `nginx-mailcow` ping phpmyadmin?

btw, what happens for me if i type http://mailcow.host:8181 in my browser, it automatically forwards to `https://...` and says it can't open the page, because it could not establish a secure connection. That's because of the browser cache .. if you remove it, it goes to http://...

so make sure your bowser cache is cleared

**Comment by rucksman** [comment]
Yes, I can ping phpmyadmin, nevertheless the phpmyadmin server does not respond in the browser (browser is completely fresh, so no temp files or cookies or whatever). One thing to know: I have installed portainer as described here: [https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/](https://mailcow.github.io/mailcow-dockerized-docs/third_party-portainer/)

**Comment by chaosbunker** [comment]
Hm, that's strange - I have no idea why it doesn't work for you. I doubt Portainer would be the problem, though. Sorry .. maybe, someone else has a better understanding?

**Comment by sriccio** [comment]
Hi,

I'm trying too to have phpmyadmin container and using mailcow's nginx to reverse proxy it for https etc.

in docker-compose.override.yml
```
    phpmyadmin-mailcow:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: "mysql"
        PMA_ABSOLUTE_URI: "https://${MAILCOW_HOSTNAME}/pma/"
      restart: always
      ports:
        - 8080:80
      volumes:
        - /sessions
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - phpmyadmin
```

in data/conf/nginx/site.phpmyadmin.custom
```
 location /pma/ {
    proxy_http_version 1.1;
    proxy_set_header Host              $http_host;   # required for docker client's sake
    proxy_set_header X-Real-IP         $remote_addr; # pass on real client's IP
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_read_timeout                 900;

    proxy_set_header Connection "";
    proxy_buffers 32 4k;
    proxy_pass http://phpmyadmin/;
}
```

I can successfully use `https://mailcowserver/pma/` but some assets aren't loaded correctly.
However I found out that the assets not being loaded are php files such as `/pma/phpmyadmin.css.php`.

They are all files ending with php. So I think here is the problem:

in mailcow's nginx `site.conf` there is a global directive to redirect .php files to phpfpm:
```
  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass phpfpm:9000;
    fastcgi_index index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    fastcgi_param PHP_VALUE "max_execution_time = 1200
                             max_input_time = 1200
                             memory_limit = 64M";
    fastcgi_read_timeout 1200;
  }
```
And it seems to "win" the fight against the `location /pma/` directive. Therefore the requests are not forwarder to the phpmyadmin container.

Any nginx master chief has an idea about how I could avoid this without modding the stock `site.conf` ?

Thanks :)
