### ISSUE TITLE
Adaptive Light/Dark custom Logo

### ISSUE THREAD

**Issue by RafaelKr** [mailcow/mailcow-dockerized#5421]
### Summary

I'd like to have the possibility to use different colored Logos in the customization settings based on light/dark mode.

### Motivation

Our company Logo is available in (nearly) black and in white.

### Additional context

I tried to use an SVG with adaptive styling, but the Logo is implemented with an `<img>`-tag, so this doesn't work.
```css
.st0{fill:#010202;}
@media (prefers-color-scheme: dark) {
    .st0{fill:#FFFFFF;}
}
```

Edit: I just noticed `prefers-color-scheme` doesn't make sense in this case as we have a toggle anyways.

Possible solutions:
- Add class `light`/`dark` to body, render SVG inline (Needs to be sanitized to prevent XSS!) [preferred]
- Upload 2 different logos
