### ISSUE TITLE
Can't start docker after Kernel update (4.9)

### ISSUE THREAD

**Issue by DJIronic** [mailcow/mailcow-dockerized#769]
I have problem with mailcow-dockerized after updating Kernel.

1) I updated it, there was  a problem with Docker launching, so I deleted  "aufs" folder as was mentioned here in https://github.com/mailcow/mailcow-dockerized/issues/309 (I also used guide how to update the kernel from this page.

2) now whem I go into /home/mailcow-dockerized folder and I try to run `docker-compose up -d` I get this:
```
root@MailServer:/home/mailcow-dockerized# docker-compose up -d
Pulling pdns-mailcow (andryyy/mailcow-dockerized:pdns)...
ERROR: repository andryyy/mailcow-dockerized not found: does not exist or no pull access
root@MailServer:/home/mailcow-dockerized#
```

Server Details:
Debian 8: Linux MailServer 4.9.0-0.bpo.4-amd64 #1 SMP Debian 4.9.51-1~bpo8+1 (2017-10-17) x86_64 GNU/Linux
RAM: 2GB
CPU: 2  (3,39Ghz) cores
Gigabit network (OVH)

So now I can't start mailcow-dockerized.
I want to run it with actual configuration, I did the update because of many random server freezes (no full memory). So now I want to keep my data at the first place. This going to be a long night for me as this is our company server and they need to access their mails..I know..I should do the snaphshot in VMware before this action..I was tired.

Thank you so much for your help. :)

**Comment by DJIronic** [comment]
And...I just realized that Docker can't see any of my containers (using `docker ps` command). 👎 

https://i.imgur.com/hceZC9R.png

**Comment by mkuron** [comment]
It says `pdns-mailcow` in the output you provided. Are you running some ancient version of Mailcow? We haven‘t been using PowerDNS for a long time... If you want to bring up this old version, you need to build all images manually:
```
docker-compose build
docker-compose up --no-build -d
```

**Comment by DJIronic** [comment]
It was not managed by me for a long time. I was deployed on another projects => it was nto my job to take care about this server...and they called me "something is not working". So...I don't know. :/ But Thank you for your answer!

`docker-compose build`: 
![image](https://user-images.githubusercontent.com/9658012/33145907-6eba39ae-cfc2-11e7-9ae8-a4b8449bf527.png)

`docker-compose up --no-pull -d`:
![image](https://user-images.githubusercontent.com/9658012/33145941-8dc302fe-cfc2-11e7-9001-1ec416378dee.png)

**Comment by mkuron** [comment]
This seems to be an older docker-compose version. Please remove all `image:` lines from docker-compose.yml and try `docker-compose up -d`.

**Comment by DJIronic** [comment]
I just removed all lines containing `image:` and I got this:
![image](https://user-images.githubusercontent.com/9658012/33146454-83aa7084-cfc4-11e7-8db7-3014a615bec4.png)

**Comment by mkuron** [comment]
Then you need an appropriate dockerfile line to the rspamd-mailcow section in docker-compose.yml. That was peobably missing in the version you are using.

**Comment by DJIronic** [comment]
OK...and where I can get it? Sorry...I am totally new to docker..Mailcow is my first thing running on it. 

So sorry for dumb questions.

**Comment by DJIronic** [comment]
OK, I tried to change `image:` link for rspamd-mailcow from actual docker-compose.yml from GitHub. Then it asked for nearly every other app in the same way so I was replacing links the new ones from actual [github file](https://user-images.githubusercontent.com/9658012/33146454-83aa7084-cfc4-11e7-8db7-3014a615bec4.png)...and now it´s asking for `image:` link for pdns-mailcow:

![image](https://user-images.githubusercontent.com/9658012/33148714-254fdeda-cfcd-11e7-835b-9c50bbb06626.png)

So I don't know, if I did it right to get  "_an appropriate dockerfile line_" and don't know, what to do now.

**Comment by mkuron** [comment]
What commit are you on?

**Comment by DJIronic** [comment]
I am not sure where to get it, but mailcow-dockerized was installed 22.2. 2017 (read from last edit on some folders).

**Comment by mkuron** [comment]
`git log` or `git describe` should tell you.

**Comment by DJIronic** [comment]
This is the top of history file, seems like last commit from Andryyy is  `15bffcd447c669453a521d69d659eeaddad31345` and from André Peters it´s `2ebdb4a54ba69a649e751b56ff9860cdc0cdd240`


![image](https://user-images.githubusercontent.com/9658012/33150355-5c236638-cfd3-11e7-9879-481ddbff146b.png)

**Comment by mkuron** [comment]
I think you didn‘t make the right modifications to the docker-compose.yml file. You need to delete the `image:` lines and add ones like `build: ./data/Dockerfiles/pdns`, using the correct directory instead of _pdns_ for every service.

**Comment by DJIronic** [comment]
OK, I started to removing all image lines like `image: andryyy/mailcow-dockerized:dovecot` but there is no line with `build` but I just met something like this: 

```
      depends_on:
        - pdns-mailcow
```

OK...to make it clear, [here](https://hastebin.com/ozaxibukim.http) is my actual (original docker-compose.yml). and[ this](https://hastebin.com/zekomoqusa.http) is what I am doing with it (changed first few servicies)...is that right?

**Comment by mkuron** [comment]
No, you need to add new build lines to every service. And don’t modify the dependencies.

**Comment by DJIronic** [comment]
OK...I am so sorry...you must by totally angry at me now for my stupidity...so sorry, I am trying.

Did I get it now?

```
services:
    pdns-mailcow:
      build: ./data/Dockerfiles/pdns
      depends_on:
        mysql-mailcow:
          condition: service_healthy
      volumes:
        - ./data/conf/pdns/:/etc/powerdns/
      restart: always
      networks:
        mailcow-network:
          ipv4_address: 172.22.1.254
          aliases:
            - pdns

    mysql-mailcow:
      build: ./data/Dockerfiles/mysl
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "--host", "localhost", "--silent"]
        interval: 10s
        timeout: 30s
        retries: 5
      volumes:
        - mysql-vol-1:/var/lib/mysql/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      environment:
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      networks:
        mailcow-network:
          aliases:
            - mysql

    redis-mailcow:
      build: ./data/Dockerfiles/redis
      depends_on:
        - pdns-mailcow
      volumes:
        - redis-vol-1:/data/
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - redis
```
